### ISSUE TITLE
✨ Implement the Data Request input

### ISSUE THREAD

**Issue by FranklinWaller** [sedaprotocol/seda-overlay#37]
## ✨ Feature

Implement the Data Request input parameter and pass it to the VM

## Motivation

This allows the user to customise the Data Request and behave differently on the input

## Implementation

* Pass the input parameters as args inside of Wasmer

**Comment by gluax** [comment]
@FranklinWaller can we get more details on this ticket? I'm not sure where or how this would want to be done? I know we can already pass args to VmCalls, so is this adding a field onto the `DataRequest` struct in `comon/src/data_request.rs` to allow for arguments? Or is it that the execute method in the consensus wasm binary should now take a vec of args and use them somehow?

**Comment by FranklinWaller** [comment]
@gluax Yes this is a simple task to couple the data request args from the seda chain to vm call args
