### ISSUE TITLE
✨ Way to derive Private Key

### ISSUE THREAD

**Issue by gluax** [sedaprotocol/seda-overlay#42]
## ✨ Feature

The user should be able to derive their private key from the overlay node since it's required for usage.

## Motivation

It's inconvenient to derive your private key right now (because only mnemonics are shown), and we should have a more straightforward way of doing so.

## Implementation

A CLI command could be added that takes the user's mnemonic as input, derives the private key for the user, and writes it to a file or to stdout.

**Comment by FranklinWaller** [comment]
Update to the issue: We don't need a CLI command for this anymore. The user should be able to either put in a `private_key` / `private_key_env` or a `mnemonic` / `mnemonic_key_env`
